server:
  port: 9000

spring:
  application:
    name: AuthenticationServer

    profiles:
      active: dev

    cloud:
      config:
        enabled: true
  eureka:
    instance:
      preferIpAddress: true

    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  data:
    dynamodb:
      entity2ddl:
        auto: create-only



