package com.authorization.server.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.authorization.server.converter.ObjectPropertyConverter;
import org.springframework.data.annotation.Id;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.io.Serializable;
import java.util.*;

@DynamoDBTable(tableName = "User")
public class User implements Serializable, UserDetails {

    @Id
    @DynamoDBTypeConverted(converter = ObjectPropertyConverter.class)
    private UserPrimaryKey key;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    private String phone;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    public User() {
        this.key = new UserPrimaryKey();
    }

    public UserPrimaryKey getKey() {
        return key;
    }

    public void setKey(UserPrimaryKey key) {
        this.key = key;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return key.getId();
    }

    public void setId(String id) {
        this.key.setId(id);
    }

    @DynamoDBRangeKey
    public String getEmail() {
        return key.getEmail();
    }

    public void setEmail(String email) {
        this.key.setId(email);
    }

    @Override
    @DynamoDBIgnore
    public Set<? extends GrantedAuthority> getAuthorities() {
        Set<GrantedAuthority> authorities = new HashSet<>();
        authorities.add(new SimpleGrantedAuthority("User"));

        return authorities;
    }

    @Override
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    @DynamoDBIgnore
    public String getUsername() {
        return key.getEmail();
    }

    @Override
    @DynamoDBIgnore
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    @DynamoDBIgnore
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    @DynamoDBIgnore
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    @DynamoDBIgnore
    public boolean isEnabled() {
        return true;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


}